import logging
import random
from typing import Any, Dict, List, Text

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from transformers import pipeline


class ActionProvideDietTips(Action):

    def name(self) -> Text:
        return "action_provide_diet_tips"

    def __init__(self):
        self.diet_data = {
            "BUTTER,WITH SALT": "contains 717 kcal",
            "BUTTER,WHIPPED,W/ SALT": "contains 718 kcal",
            "BUTTER OIL,ANHYDROUS": "contains 876 kcal",
            "CHEESE,BLUE": "contains 353 kcal",
            "CHEESE,BRICK": "contains 371 kcal",
            "CHEESE,BRIE": "contains 334 kcal",
            "CHEESE,CAMEMBERT": "contains 300 kcal",
            "CHEESE,CARAWAY": "contains 376 kcal",
            "CHEESE,CHEDDAR": "contains 404 kcal",
            "CHEESE,CHESHIRE": "contains 387 kcal",
            "CHEESE,COLBY": "contains 394 kcal",
            "CHEESE,COTTAGE,CRMD,LRG OR SML CURD": "contains 98 kcal",
            "CHEESE,COTTAGE,CRMD,W/FRUIT": "contains 97 kcal",
            "CHEESE,COTTAGE,NONFAT,UNCRMD,DRY,LRG OR SML CURD": "contains 72 kcal",
            "CHEESE,COTTAGE,LOWFAT,2% MILKFAT": "contains 81 kcal",
            "CHEESE,COTTAGE,LOWFAT,1% MILKFAT": "contains 72 kcal",
            "CHEESE,CREAM": "contains 350 kcal",
            "CHEESE,EDAM": "contains 357 kcal",
            "CHEESE,FETA": "contains 264 kcal",
            "CHEESE,FONTINA": "contains 389 kcal",
            "CHEESE,GJETOST": "contains 466 kcal",
            "CHEESE,GOUDA": "contains 356 kcal",
            "CHEESE,GRUYERE": "contains 413 kcal",
            "CHEESE,LIMBURGER": "contains 327 kcal",
            "CHEESE,MONTEREY": "contains 373 kcal",
            "CHEESE,MOZZARELLA,WHL MILK": "contains 300 kcal",
            "CHEESE,MOZZARELLA,WHL MILK,LO MOIST": "contains 318 kcal",
            "CHEESE,MOZZARELLA,PART SKIM MILK": "contains 254 kcal",
            "CHEESE,MOZZARELLA,LO MOIST,PART-SKIM": "contains 295 kcal",
            "CHEESE,MUENSTER": "contains 368 kcal",
            "CHEESE,NEUFCHATEL": "contains 253 kcal",
            "CHEESE,PARMESAN,GRATED": "contains 420 kcal",
            "CHEESE,PARMESAN,HARD": "contains 392 kcal",
            "CHEESE,PORT DE SALUT": "contains 352 kcal",
            "CHEESE,PROVOLONE": "contains 351 kcal",
            "CHEESE,RICOTTA,WHOLE MILK": "contains 174 kcal",
            "CHEESE,RICOTTA,PART SKIM MILK": "contains 138 kcal",
            "CHEESE,ROMANO": "contains 387 kcal",
            "CHEESE,ROQUEFORT": "contains 369 kcal",
            "CHEESE,SWISS": "contains 393 kcal",
            "CHEESE,TILSIT": "contains 340 kcal",
            "CHEESE,PAST PROCESS,AMERICAN,FORT W/ VITAMIN D": "contains 366 kcal",
            "CHEESE,PAST PROCESS,PIMENTO": "contains 375 kcal",
            "CHEESE,PAST PROCESS,SWISS": "contains 334 kcal",
            "CHEESE FD,COLD PK,AMERICAN": "contains 331 kcal",
            "CHEESE FD,PAST PROCESS,AMERICAN,VITAMIN D FORT": "contains 330 kcal",
            "CHEESE FD,PAST PROCESS,SWISS": "contains 323 kcal",
            "CHEESE SPRD,PAST PROCESS,AMERICAN": "contains 290 kcal",
            "CREAM,FLUID,HALF AND HALF": "contains 123 kcal",
            "CREAM,FLUID,LT (COFFEE CRM OR TABLE CRM)": "contains 191 kcal",
            "CREAM,FLUID,LT WHIPPING": "contains 292 kcal",
            "CREAM,FLUID,HVY WHIPPING": "contains 340 kcal",
            "CREAM,WHIPPED,CRM TOPPING,PRESSURIZED": "contains 257 kcal",
            "CREAM,SOUR,RED FAT,CULTURED": "contains 135 kcal",
            "CREAM,SOUR,CULTURED": "contains 198 kcal",
            "EGGNOG": "contains 88 kcal",
            "SOUR DRSNG,NON-BUTTERFAT,CULTURED,FILLED CREAM-TYPE": "contains 178 kcal",
            "MILK,FILLED,FLUID,W/BLEND OF HYDR VEG OILS": "contains 63 kcal",
            "MILK,FILLED,FLUID,W/LAURIC ACID OIL": "contains 63 kcal",
            "CHEESE,AMERICAN,NONFAT OR FAT FREE": "contains 126 kcal",
            "CREAM SUB,LIQ,W/HYDR VEG OIL&SOY PROT": "contains 136 kcal",
            "CREAM SUB,LIQ,W/LAURIC ACID OIL&NA CASEINATE": "contains 136 kcal",
            "CREAM SUBSTITUTE,POWDERED": "contains 529 kcal",
            "DESSERT TOPPING,POWDERED": "contains 577 kcal",
            "DESSERT TOPPING,PDR,1.5 OZ PREP W/1/2 CUP MILK": "contains 194 kcal",
            "DESSERT TOPPING,PRESSURIZED": "contains 264 kcal",
            "DESSERT TOPPING,SEMI SOLID,FRZ": "contains 318 kcal",
            "SOUR CRM,IMITN,CULTURED": "contains 208 kcal",
            "MILK SUBSTITUTES,FLUID,W/LAURIC ACID OIL": "contains 61 kcal",
            "MILK,WHL,3.25% MILKFAT,W/ ADDED VITAMIN D": "contains 61 kcal",
            "MILK,PRODUCER,FLUID,3.7% MILKFAT": "contains 64 kcal",
            "MILK,RED FAT,FLUID,2% MILKFAT,W/ ADDED VIT A & VITAMIN D": "contains 50 kcal",
            "MILK,RED FAT,FLUID,2% MILKFAT,W/ ADDED NFMS, VIT A & VIT D": "contains 51 kcal",
            "MILK,RED FAT,FLUID,2% MILKFAT,PROT FORT,W/ ADDED VIT A & D": "contains 56 kcal",
            "MILK,LOWFAT,FLUID,1% MILKFAT,W/ ADDED VIT A & VITAMIN D": "contains 42 kcal",
            "MILK,LOWFAT,FLUID,1% MILKFAT,W/ ADD NONFAT MILK SOL,VIT A/ D": "contains 43 kcal",
            "MILK,LOWFAT,FLUID,1% MILKFAT,PROT FORT,W/ ADDED VIT A & D": "contains 48 kcal",
            "MILK,NONFAT,FLUID,W/ ADDED VIT A & VIT D (FAT FREE OR SKIM)": "contains 34 kcal",
            "BABYFOOD,VEG,PEAS,STR": "contains 50 kcal",
            "BABYFOOD,PEAS,DICES,TODD": "contains 64 kcal",
            "BABYFOOD,VEG,SPINACH,CRMD,STR": "contains 37 kcal",
            "BABYFOOD,FRUIT,APRICOT W/TAPIOCA,JR": "contains 63 kcal",
            "BABYFOOD,FRUIT,BANANAS W/TAPIOCA,STR": "contains 56 kcal",
            "BABYFOOD,FRUIT,PEACHES,STR": "contains 65 kcal",
            "BABYFOOD,FRUIT,PEACHES,JR": "contains 65 kcal",
            "BABYFOOD,FRUIT,PEARS,STR": "contains 42 kcal",
            "BABYFOOD,FRUIT,PEARS,JR": "contains 44 kcal",
            "BABYFOOD,FRUIT,PLUMS W/TAPIOCA,WO/VIT C,STR": "contains 71 kcal",
            "BABYFOOD,FRUIT,PLUMS W/TAPIOCA,WO/VIT C,JR": "contains 74 kcal",
            "BABYFOOD,FRUIT,PRUNES W/TAPIOCA,WO/VIT C,STR": "contains 69 kcal",
            "BABYFOOD,FRUIT,PRUNES W/TAPIOCA,WO/VIT C,JR": "contains 70 kcal",
            "BABYFOOD,PRUNES,WO/VIT C,STR": "contains 100 kcal",
            "BABYFOOD,FRUIT DSSRT,MANGO W/ TAPIOCA": "contains 70 kcal",
            "BABYFOOD,PEARS,DICES,TODD": "contains 57 kcal",
            "BABYFOOD,FRUIT,APPLSAUC&APRICOTS,STR": "contains 44 kcal",
            "BABYFOOD,FRUIT,APPLSAUC&APRICOTS,JR": "contains 47 kcal",
            "BABYFOOD,FRUIT,APPLSAUC&CHERRIES,STR": "contains 51 kcal",
            "BABYFOOD,FRUIT,APPLSAUC & CHERRIES,JR": "contains 51 kcal",
            "BABYFOOD,FRUIT,APPLSAUC W/BANANA,JR": "contains 66 kcal",
            "BABYFOOD,FRUIT,APPLSAUC&PNAPPL,STR": "contains 37 kcal",
            "BABYFOOD,FRUIT,APPLSAUC&PNAPPL,JR": "contains 39 kcal",
            "BABYFOOD,FRUIT,APPL & RASPBERRY,STR": "contains 58 kcal",
            "BABYFOOD,FRUIT,APPL & RASPBERRY,JR": "contains 58 kcal",
            "BABYFOOD,FRUIT & VEG,APPL & SWT POTATO": "contains 64 kcal",
            "BABYFOOD,FRUIT,BANANAS&PNAPPL W/TAPIOCA,JR": "contains 68 kcal",
            "BABYFOOD,FRUIT,BANANAS&PNAPPL W/TAPIOCA,STR": "contains 65 kcal",
            "BABYFOOD,FRUIT,PEARS&PNAPPL,STR": "contains 41 kcal",
            "BABYFOOD,FRUIT,PEARS&PNAPPL,JR": "contains 44 kcal",
            "BABYFOOD,FRUIT,GUAVA&PAPAYA W/TAPIOCA,STR": "contains 63 kcal",
            "BABYFOOD,PEACHES,DICES,TODD": "contains 51 kcal",
            "BABYFOOD,FRUIT,PAPAYA&APPLSAUC W/TAPIOCA,STR": "contains 70 kcal",
            "BABYFOOD,FRUIT,BANANAS W/APPLS&PEARS,STR": "contains 83 kcal",
            "BABYFOOD,FRUIT,APPL&BLUEBERRY,STR": "contains 61 kcal",
            "BABYFOOD,FRUIT,APPL&BLUEBERRY,JR": "contains 62 kcal",
            "BABYFOOD,JUICE,APPLE": "contains 47 kcal",
            "BABYFOOD,APPLE-BANANA JUC": "contains 51 kcal",
            "BABYFOOD,JUC,APPL&PEACH": "contains 43 kcal",
            "BABYFOOD,APPLE-CRANBERRY JUC": "contains 46 kcal",
            "BABYFOOD,JUC,APPL&PLUM": "contains 49 kcal",
            "BABYFOOD,JUC,APPL&PRUNE": "contains 72 kcal",
            "BABYFOOD,JUICE,ORANGE": "contains 45 kcal",
            "BABYFOOD,JUC,ORANGE&APPL": "contains 43 kcal",
            "BABYFOOD,JUC,ORANGE&APPL&BANANA": "contains 47 kcal",
            "BABYFOOD,JUC,ORANGE&APRICOT": "contains 46 kcal",
            "BABYFOOD,JUC,ORANGE&BANANA": "contains 50 kcal",
            "BABYFOOD,JUC,ORANGE&PNAPPL": "contains 48 kcal",
            "BABYFOOD,JUC,PRUNE&ORANGE": "contains 70 kcal",
            "BABYFOOD,JUC,MXD FRUIT": "contains 47 kcal",
            "BABYFOOD,CRL,BARLEY,DRY FORT": "contains 376 kcal",
            "BABYFOOD,CRL,WHL WHEAT,W/ APPLS,DRY FORT": "contains 402 kcal",
            "BABYFOOD,CRL,MXD,DRY FORT": "contains 399 kcal",
            "BABYFOOD,CRL,MXD,W/ BANANAS,DRY": "contains 391 kcal",
            "BABYFOOD,CRL,MXD,W/ APPLSAUC & BANANAS,STR": "contains 82 kcal",
            "BABYFOOD,CRL,MXD,W/ APPLSAUC & BANANAS,JR,FORT": "contains 84 kcal",
            "BABYFOOD,CRL,OATMEAL,DRY FORT": "contains 394 kcal",
            "BABYFOOD,CRL,OATMEAL,W/ BANANAS,DRY": "contains 399 kcal",
            "BABYFOOD,CRL,OATMEAL,W/ APPLSAUC & BANANAS,STR": "contains 75 kcal",
            "BABYFOOD,CRL,OATMEAL,W/ APPLSAUC & BANANAS,JR,FORT": "contains 76 kcal"
        }

    def run(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict[str, Any]) -> List[Dict[str, Any]]:
        query = tracker.latest_message.get('text').lower()
        if "tell me about" in query:
            item = query.replace("tell me about ", "").upper()
            if item in self.diet_data:
                dispatcher.utter_message(text=f"{item} {self.diet_data[item]}")
            else:
                dispatcher.utter_message(text="Sorry, I don't have information on that item.")
        else:
            random_item = random.choice(list(self.diet_data.items()))
            dispatcher.utt

class ActionProvideExerciseInfo(Action):

    def name(self) -> str:
        return "action_provide_exercise_info"

    def __init__(self):
        super().__init__()
        self.exercise_data = {
            "partner plank band row": "The partner plank band row is an abdominal exercise where two partners perform single-arm planks while pulling on the opposite ends of an exercise band. This technique can be done for time or reps in any ab-focused workout.",
            "dumbbell hollow-body floor press": "The dumbbell hollow-body floor press combines upper-body strength and core work in one move.",
            "dumbbell straight-legged hip raise": "The dumbbell straight-legged hip raise works the hips and glutes. It requires and teaches body control and coordination.",
            "seated leg tuck with dumbbell": "The seated leg tuck with dumbbell is an ab exercise requiring only a bench and a dumbbell. It's commonly performed for high reps as a burnout at the end of a core workout.",
            "sledgehammer swing": "The sledgehammer swing is an exercise working the abdominals and numerous other muscles. The sledgehammer is slammed from overhead onto a tire which absorbs the impact and causes the hammer to bounce back up. It can be performed for time or reps as part of a functional fitness or athleticism-focused workout.",
            "seated twist with PVC pipe": "The seated bar twist is a core exercise aiming to strengthen the obliques.",
            "decline press sit-up": "The decline bar press sit-up is a core and upper body exercise targeting the lower abdominals and shoulders.",
            "single-arm high-cable side bend": "The single-arm high-cable side bend is an exercise targeting the obliques using a cable stack machine.",
            "standing cable wood chop": "The standing cable high-to-low twist is a core exercise targeting the lower abdominals and the obliques.",
            "pallof press with rotation": "The Pallof press with rotation is a dynamic variation of the Pallof press that incorporates weighted rotation away from the torso using resistance from a cable pulley. It is intended to build abdominal strength and teach proper bracing. It can be performed for time or for reps in the core-focused portion of any workout.",
            "cable lying twist on ball": "The cable lying twist on ball is an exercise targeting the core and obliques with the added challenge of stability to keep from losing position on the unstable surface.",
            "single-arm cable outward-facing biceps curl": "The single-arm cable outward-facing biceps curl is a cable exercise that targets the biceps. It is performed standing in front of a cable machine facing away from the cable stack to increase the range of motion by fully extending the elbows. This movement is usually performed for moderate to high reps for a burn and pump as part of an arm-focused workout.",
            "smith machine V-up": "The smith machine V-up is a weighted abdominal exercise that involves pressing a weighted bar upward while performing a V-up. Performing it in a Smith machine eliminates the balance challenge of a free weight. It is usually performed for moderate to high reps in the ab-focused portion of a workout.",
            "decline crunch": "The decline crunch is an effective core exercise targeting the rectus abdominis.",
            "knees tucked crunch": "The knees tucked crunch is a core exercise that involves performing a crunch while keeping the knees bent in a 90-degree position. It primarily targets the rectus abdominis or 'six-pack' muscles. It can be performed for time or reps as part of any abs-focused circuit or workout.",
            "bent-knee reverse crunch": "The bent-knee reverse crunch is a popular bodyweight core exercise. It targets the lower portion of the rectus abdominis or 'six-pack' muscles. It can be performed for time or reps as part of any ab-focused workout.",
            "lying oblique crunch": "The lying oblique crunch is a bodyweight exercise targeting the oblique muscles. It can be performed for a specific number of reps or to fatigue or failure as part of the ab-focused portion of any workout.",
            "wall mountain climber": "The wall mountain climber is a challenging exercise targeting the shoulders and abdominals. It's most common in bodyweight circuit training because it targets a lot of muscles as well as the cardiovascular system all at once. It can be performed for time or reps.",
            "partner lying leg raise with lateral throw down": "The partner lying leg raise with lateral throw down is a core exercise in which one partner performs a leg raise while the other partner pushes their legs back down at a lateral angle. The partner performing the exercise has to use core strength and stability to keep their legs from falling to the ground.",
            "partner sit-up with high-five": "The partner sit-up with high-five is a full-body exercise targeting the core. Partners each perform a sit-up and high-five each other mid rep.",
            "exercise ball knee roll-in": "The exercise ball knee roll-in is an abdominal exercise that involves supporting yourself with your hands in a plank or push-up position and drawing the knees in toward the chest. This is a fairly advanced abdominal move requiring a fair amount of core strength.",
            "partner lying leg raise with throw down": "The partner lying leg raise with throw down is a core exercise in which one partner performs a leg raise while the other partner pushes their legs back down. The partner performing the exercise has to use core strength and stability to keep their legs from falling to the ground.",
            "reach crunch": "The reach crunch is a bodyweight core exercise that involves keeping the arms raised toward the ceiling while performing a crunch. It can be performed for time or reps as part of any abs-focused circuit or workout.",
            "V-up plus knee-to-chest combo": "The V-up plus knee-to-chest combo is a core exercise that targets the abdominals and hip flexors by combining two movements into a single sequence. It can be performed for time or reps in the ab-focused portion of any workout.",
            "tip-toe crunch": "The tip-toe crunch is a variation on the crunch exercise that involves placing the toes on or near the ground. This can help isolate the abs from the hip flexors. The tip-toe crunch can be performed for time or for reps as part of the core-focused component of any workout.",
            "seated leg lift": "The seated leg lift is a bodyweight exercise targeting the muscles of the core and hip flexors. It can be performed for time or reps in the core-focused portion of any workout.",
            "FYR knees to chest": "The hollow-body alternating knee-to-chest is a core exercise that involves bending the legs while holding the hips and shoulder blades off the ground. It targets the rectus abdominis or 'six-pack' muscles. It can be performed for time or reps in the ab-focused portion of any workout.",
            "FYR leg lift": "The seated leg lift is a bodyweight exercise targeting the muscles of the core and hip flexors. It can be performed for time or reps in the core-focused portion of any workout.",
            "ab wheel roll-out": "The ab wheel roll-out is an exercise targeting the abdominals using an inexpensive wheel device with a handle on either side. Many trainers and strength coaches claim it's one of the best exercises for developing strength in the midsection. Beginners may have to start with a limited range of motion or just wheel planks.",
            "decline reverse crunch": "The decline reverse crunch is a core exercise targeting the lower abdominals.",
            "chin-up crunch": "The chin-up crunch is an exercise targeting the core and overall upper-body strength. It combines a chin-up with a knee raise or crunch to give extra emphasis to the core.",
            "cat-cow": "Cat-cow is a traditional yoga pose that is also popular in fitness and strength training. It targets spinal mobility and control of the vertebral column. It can be performed for time or reps as part of a dynamic warm-up or as a mobility or restorative exercise anytime. It can also work as part of a yoga or bodyweight sequence with other poses.",
            "lunge with overhead reach": "The lunge with overhead reach is a full-body bodyweight movement targeting the quads and shoulders. It has both strength and mobility benefits and can be performed one leg at a time or alternating for time or for reps.",
            "hand shift plank": "The hand shift plank is a progression of the straight-arm plank exercise where you maintain a plank position as you shift your hands side to side. The additional movement forces the core muscles to work harder to stabilize.",
            "exercise ball pull-in": "The exercise ball knee roll-in is an abdominal exercise that involves supporting yourself with your hands in a plank or push-up position and drawing the knees in toward the chest. This is a fairly advanced abdominal move requiring core strength.",
            "exercise ball knee tuck - Gethin variation": "The exercise ball knee roll-in is an abdominal exercise that involves supporting yourself with your hands in a plank or push-up position and drawing the knees in toward the chest. This is a fairly advanced abdominal move requiring core strength.",
            "alternating exercise ball knee tucks - Gethin variation": "The exercise ball knee roll-in is an abdominal exercise that involves supporting yourself with your hands in a plank or push-up position and drawing the knees in toward the chest. This is a fairly advanced abdominal move requiring core strength.",
             "BOSU knee tuck": "The BOSU knee tuck is a dynamic abdominal movement performed on a BOSU ball or other stability training device. It primarily targets the rectus abdominis or 'six-pack' muscles of the core. It can be performed for time or reps as part of an ab-focused workout or a circuit involving body weight or the BOSU ball.",
            "standing hip circle": "The standing hip circle is a bodyweight exercise targeting the hips and abductor muscles. It is a classic way to 'limber up' after sitting for a long period or before a lower-body workout or sports. It requires no equipment and can be helpful for everyone from beginners to advanced fitness enthusiasts.",
            "banded hammer press - Gethin variation": "The machine chest press is an upper body exercise targeting the pectoral muscles.",
            "EZ-bar spider curl - Gethin variation": "The EZ-bar spider curl is an isolation exercise targeting the biceps and performed face-down on an incline bench. The EZ-bar makes for a more comfortable wrist position.",
            "standing band biceps curl": "The standing band biceps curl is an arm-focused exercise using a band for resistance. This variation is usually performed for moderate to high reps as part of an arms-focused or upper-body workout.",
            "Paul Carter incline dumbbell biceps curl": "The incline dumbbell biceps curl is an isolation exercise targeting the biceps. This variation targets the long head of the biceps more than a traditional curl and there is more overall tension to this muscle.",
            "FYR kneeling biceps": "The kneeling concentration curl allows you to target the biceps without having the ability to use momentum from the rest of your body to move the weight.",
            "TBS incline dumbbell curl": "The incline dumbbell biceps curl is an isolation exercise targeting the biceps. This variation targets the long head of the biceps more than a traditional curl and there is more overall tension to this muscle.",
            "incline dumbbell curl - Gethin variation": "The incline dumbbell biceps curl is an isolation exercise targeting the biceps. This variation targets the long head of the biceps more than a traditional curl and there is more overall tension to this muscle.",
            "lying cable curl - Gethin variation": "The lying cable biceps curl is an isolation exercise that eliminates the possibility of using momentum from the lower body to raise the weight.",
            "standing one-arm cable curl": "The single-arm cable biceps curl is a single-joint isolation exercise for building the biceps. This move is intended to be strict and deliberate; this is not an exercise for using momentum or otherwise cheating.",
            "lying close-grip bar curl on high pulley": "The lying high-cable biceps curl is an unusual move for building the biceps—but it’s a highly effective one. Lying prone and curling down toward you provides a different stimulus than more standard approaches allow.",
            "lying high-cable biceps curl": "The lying high-cable biceps curl is a single-joint exercise targeting the biceps in a prone (face-up) position. It is usually performed for moderate to high reps as part of the arm-focused portion of a workout.",
            "high cable curls": "The lying high-cable biceps curl is a single-joint exercise targeting the biceps in a prone (face-up) position. It is usually performed for moderate to high reps as part of the arm-focused portion of a workout.",
            "seated cable biceps curl": "The seated cable biceps curl is a single-joint arm exercise intended to isolate the biceps. The seated position helps eliminate the use of momentum. This movement is usually performed for moderate to high reps for a burn and pump as part of an arm-focused workout.",
            "machine preacher curls": "The machine preacher curl is an isolation exercise targeting the biceps.",
            "standing calf raise facing hack squat machine - Gethin variation": "The reverse hack squat calf raise is a variation of the standing calf raise to target them in a different manner.",
            "calf press on a hack squat machine - Gethin variation": "The hack squat calf raise is a variation of the standing calf raise to target them in a different manner than seated or fully standing.",
            "wall calf stretch": "The wall calf stretch is a stretch targeting the calf muscles. This is a simple way to stretch these often-tight muscles without any equipment needed.",
            "barbell incline bench press medium-grip": "The incline bench press is an upper body compound movement that targets the upper chest.",
            "Paul Carter incline bench press": "The incline bench press is an upper body compound movement that targets the upper chest.",
            "TBS close-grip bench press": "The close-grip bench press is a compound exercise targeting the triceps and chest. The main difference between this exercise and the standard bench press is that the hands and elbows are placed closer together.",
            "UP close-grip bench press": "The close-grip bench press is a compound exercise targeting the triceps and chest. The main difference between this exercise and the standard bench press is that the hands and elbows are placed closer together.",
            "King Maker incline barbell bench press": "The incline bench press is an upper body compound movement that targets the upper chest.",
            "isometric wipers": "The typewriter push-up is an advanced push-up variation where the hands are extra wide and you lower toward each hand in alternating reps. It is more challenging to each working arm than traditional push-ups and also stretches and challenges the chest.",
            "tiger-bend push-up": "The tiger-bend push-up is an advanced push-up variation where you shift onto your forearms at the bottom position and then back onto your hands and up again. It targets the triceps far more than regular push-ups.",
            "side-to-side push-up": "The side-to-side push-up is a variation of the push-up exercise where you side-step the opposite hand and foot and perform a push-up.",
            "typewriter push-up": "The typewriter push-up is an advanced push-up variation where the hands are extra wide and you lower toward each hand in alternating reps. It is more challenging to each working arm than traditional push-ups and also stretches and challenges the chest.",
            "AM chest dips": "The chest dip is a chest-building exercise in which the lifter hangs between two parallel handles. Leaning the torso slightly forward shifts the emphasis from the triceps to the chest.",
            "cross-over push-up": "The cross-over push-up is a variation of the push-up that adds a degree of difficulty by stepping over a small box or step between repetitions. It can be performed for time or for reps and creates a greater core stabilization challenge by forcing the core muscles to maintain a neutral spine throughout the movement.",
            "leverage chest press": "The machine chest press is an upper body exercise targeting the pectoral muscles.",
            "Smith machine bench press throw": "The Smith machine bench press throw is an exercise that helps develop pushing power that carries over to the traditional bench press. It involves pushing a relatively light weight (such as 30-50 percent of your 1RM) explosively and actually letting go at the top of the rep. It can work as power or speed-style training in a strength or athleticism-focused workout plan.",
            "machine seated chest press - Gethin variation": "The machine chest press is an upper body exercise targeting the pectoral muscles.",
            "TBS dumbbell incline press": "The incline dumbbell bench press is an upper body exercise targeting the upper pectoral muscles.",
            "incline dumbbell press - Gethin variation": "The incline dumbbell bench press is an upper body exercise targeting the upper pectoral muscles.",
            "decline dumbbell press - Gethin variation": "The decline dumbbell bench press is an upper body isolation exercise targeting the lower chest. Utilizing dumbbells instead of a barbell increases the difficulty of stabilizing the weight.",
            "UP incline dumbbell press": "The incline dumbbell bench press is an upper body exercise targeting the upper pectoral muscles.",
            "King Maker standing dumbbell shoulder press": "The standing dumbbell shoulder press is a classic deltoid-builder (especially the front deltoids) that’s ubiquitous in gyms around the world. Performing the move standing up as opposed to seated allows for more weight to be used.",
            "pass-through stretch with band": "The pass-through stretch with band is a popular move to build and maintain mobility in the shoulder joint and to strengthen the muscles of the upper back and rotator cuff. It is common in CrossFit and Olympic lifting training and is usually performed as part of a warm-up or paired with movements in a workout. It can also be performed with a PVC pipe or dowel if a band isn't available.",
            "Svend press": "The Svend press is an exercise where the chest is targeted by performing presses while squeezing two weight plates together. It is usually performed for relatively high reps with light weights as an accessory movement to the bench press or as a burnout movement on chest day.",
            "plate halo": "The plate halo is an exercise targeting the shoulder complex. It's usually performed as part of a dynamic warm-up prior to an upper-body workout.",
            "cable rope pull-through deadlift": "The cable rope pull-through deadlift is an exercise targeting the glutes and hamstrings using a proper hip-hinging motion.",
            "standing hip extension": "The standing hip extension is a movement that activates the glutes and hamstrings. It is often performed either for time or reps as part of a dynamic warm-up.",
            "glute-ham raise - Gethin variation": "The glute ham raise is an exercise targeting the glutes and hamstrings on a GHD.",
            "natural glute ham raise - Gethin variation": "The glute ham raise is an exercise targeting the glutes and hamstrings on a GHD.",
            "glute ham raise": "The glute ham raise is an exercise targeting the glutes and hamstrings on a GHD.",
            "Paul Carter leg extension": "The leg extension is an isolation exercise for the quads.",
            "leg extension - Gethin variation": "The leg extension is an isolation exercise for the quads.",
            "natural glute ham raise": "The glute ham raise is an exercise targeting the glutes and hamstrings on a GHD.",
            "inchworm": "The inchworm is a popular bodyweight exercise that involves 'walking' the hands on the floor from a bent-over toe-touch position into a straight-arm plank. It is usually performed as part of a dynamic warm-up to help raise core body temperature and 'limber up' the body from head to toe.",
            "single-leg balance and reach": "The single-leg balance and reach is an exercise that focuses on lower-body strength and stability.",
            "incline dumbbell row - Gethin variation": "The incline dumbbell row is an upper body isolation exercise targeting the lower lats and upper back muscles.",
            "burpee to pull-up": "The burpee to pull-up is a variation of the bodyweight burpee in which the jump at the top of each rep leads into a jumping pull-up. It is popular in circuit-style and metcon workouts.",
            "bent-over scapular slide": "The bent-over scapular slide is an upper-body exercise that helps with scapular and shoulder mobility. It is commonly performed for time or reps as part of a dynamic warm-up for the upper body.",
            "iron cross stretch": "The iron cross stretch is a bodyweight stretch that focuses on hip and thoracic spine mobility.",
            "band deadlift": "The band deadlift is a lower-body exercise that mainly targets the hamstrings while also benefiting the glutes and lats using a proper hip-hinging motion.",
            "child's pose": "Child's pose is a traditional yoga pose that is also popular in fitness and strength training. It targets mobility of the thoracic spine and control of the vertebral column. It can be performed for time or reps as part of a dynamic warm-up or as a mobility or restorative exercise anytime. It can also work as part of a yoga or bodyweight sequence with other poses.",
            "partner side plank band row": "The partner side plank band row is an abdominal exercise where two partners perform side planks while pulling on the opposite ends of an exercise band. This technique can be done for time or reps in any ab-focused workout.",
            "TBS deficit deadlift": "The barbell deficit deadlift is a compound exercise targeting the posterior chain.",
            "leverage high row": "The machine high row is an exercise targeting the lats and works the back overall.",
            "machine low row": "The machine low row is an exercise targeting the back muscles.",
            "zercher squat": "The Zercher squat is a barbell exercise in which the bar is placed in the crease of your elbows as you perform a normal squat. This movement can be awkward at first but is extremely effective in building both size and strength.",
            "seesaw lunge": "The seesaw lunge is a bodyweight exercise that combines both the forward and the reverse lunge. It can also be performed holding dumbbells or other weights. It can be performed for time or reps in the lower-body portion of any workout.",
            "leg press": "The leg press is a machine exercise targeting the quadriceps. It’s a favorite among lifters who prefer the seated position to standing with a load on the spine.",
            "leg extensions": "The leg extension is an isolation exercise for the quads.",
            "leg press - Gethin variation": "The leg press is a machine exercise targeting the quadriceps. It’s a favorite among lifters who prefer the seated position to standing with a load on the spine.",
            "AM leg press": "The leg press is a machine exercise targeting the quadriceps. It’s a favorite among lifters who prefer the seated position to standing with a load on the spine.",
            "UP quad extension": "The leg extension is an isolation exercise for the quads.",
            "UP leg press": "The leg press is a machine exercise targeting the quadriceps. It’s a favorite among lifters who prefer the seated position to standing with a load on the spine.",
            "King Maker leg press": "The leg press is a machine exercise targeting the quadriceps. It’s a favorite among lifters who prefer the seated position to standing with a load on the spine.",
            "over bench jump": "The over bench jump is a plyometric exercise requiring only a weight bench to perform. It improves jumping ability and athleticism while burning a lot of calories.",
            "burpee tuck jump": "The burpee tuck jump is an explosive version of the burpee exercise that adds a tuck jump to the top of each rep. It can be performed for time or reps in any fat-loss or athleticism-focused circuit or workout.",
            "sprinter burpee": "The sprinter burpee is an explosive version of the burpee exercise that adds a sprinter jump to the top of each rep. It can be performed for time or reps in any fat-loss or athleticism-focused circuit or workout.",
            "barbell upright row": "The barbell upright row is a barbell exercise that builds stronger and bigger traps. Many lifters combine this move with either their back or shoulder workout since it involves both body parts.",
            "machine shoulder (military) press": "The machine shoulder press is an upper body exercise targeting the deltoids.",
            "behind-the-head push-press": "The behind-the-head push-press is an overhead press variation in which the barbell starts in the back rack position and is pushed overhead with assistance from the lower body. It is most often seen in training for Olympic weightlifting. It can be part of a barbell complex or performed for low reps focusing on power and movement quality.",
            "AM upright row": "The barbell upright row is a barbell exercise that builds stronger and bigger traps. Many lifters combine this move with either their back or shoulder workout since it involves both body parts.",
            "alternating deltoid raise": "The dumbbell front raise to lateral raise combines two exercises that build and strengthen the middle deltoids and the anterior deltoids of the shoulders.",
            "FYR dumbbell shoulder press": "The standing dumbbell shoulder press is a classic deltoid-builder (especially the front deltoids) that’s ubiquitous in gyms around the world. Performing the move standing up as opposed to seated allows for more weight to be used.",
            "FYR dumbbell front raise to lateral raise": "The dumbbell front raise to lateral raise combines two exercises that build and strengthen the middle deltoids and the anterior deltoids of the shoulders.",
            "incline front dumbbell raise - Gethin variation": "The incline dumbbell front raise is an isolation exercise targeting the shoulders.",
            "bar shoulder extension stretch": "The bar shoulder extension stretch is a technique to increase overhead mobility (known as shoulder flexion) and thoracic extension with the help of a bar or other stable object. It is often used as part of a warm-up before upper-body training.",
            "towel dumbbell front raise": "The towel dumbbell front raise is a variation of the dumbbell front raise that involves hanging a dumbbell from a towel held in the hands. It could also be performed with a kettlebell or weight plate. It can provide variety in a shoulder-focused muscle-building workout or as part of an upper-body or full-body circuit.",
            "upright row - Gethin variation": "The barbell upright row is a barbell exercise that builds stronger and bigger traps. Many lifters combine this move with either their back or shoulder workout since it involves both body parts.",
            "floor angel": "The floor angel is a stretch targeting shoulder mobility and activation of the shoulder stabilizer muscles. It also targets a range of postural muscles in the upper back.",
            "band skullcrusher": "The band skullcrusher is a variation of the popular bench exercise targeting the triceps muscles. It is usually performed for moderate to high reps as part of an upper-body or arm-focused workout.",
            "incline EZ-bar skullcrusher": "The incline EZ-bar skullcrusher is a popular exercise targeting the triceps muscles. The incline angle helps to target the long head of the triceps in particular. This exercise is usually performed for moderate to high reps as part of an upper-body or arm-focused workout.",
            "decline barbell triceps extension - Gethin variation": "The decline EZ-bar skullcrusher is an upper body isolation exercise targeting the triceps.",
            "tricep dumbbell kickback": "The single-arm triceps kick-back is an isolation move from a bent-over position used to increase size and strength of the triceps.",
            "standing bent-over one-arm dumbbell triceps extension": "The single-arm triceps kick-back is an isolation move from a bent-over position used to increase size and strength of the triceps.",
            "Paul Carter dumbbell kick-back": "The single-arm triceps kick-back is an isolation move from a bent-over position used to increase size and strength of the triceps.",
            "incline dumbbell overhead triceps extension": "The incline dumbbell overhead triceps extension is a popular exercise targeting the triceps muscles. The incline angle helps to target the long head of the triceps in particular. This exercise is usually performed for moderate to high reps as part of an upper-body or arm-focused workout.",
            "body triceps press using flat bench": "The bodyweight triceps press is an arm movement that involves performing overhead presses in a face-down position on a Smith machine or other raised bar. It is a surprisingly difficult movement that hammers all three heads of the triceps and can easily be scaled upward or downward in difficulty by moving the bar.",
            "seated triceps push-down": "The seated triceps push-down is a triceps exercise that is performed with a rope attachment. The seated position helps eliminate the use of momentum. It is usually performed for moderate to high reps as part of the arm-focused portion of a workout.",
            "kneeling cable triceps extension": "The kneeling cable triceps extension is a single-joint exercise meant to isolate the triceps muscles using a high pulley on a cable stack and a bench. It can also be performed in a tall-kneeling stance from a low pulley. It is most commonly used in muscle-building triceps or arm workouts.",
            "lying cable triceps extension": "The lying cable triceps extension is an isolation exercise performed lying on either a bench or the floor. This movement is usually performed for moderate to high reps for a burn and pump as part of an arm-focused workout.",
            "cable overhead triceps extension - Gethin variation": "The overhead triceps extension is an isolation exercise that is performed with a cable. It is usually performed for moderate to high reps as part of the arm-focused portion of a workout.",
            "single-arm incline triceps extension": "The single-arm incline triceps extension is a dumbbell exercise targeting the triceps. The incline angle helps to target the long head of the triceps in particular. This exercise is usually performed for moderate to high reps as part of an upper-body or arm-focused workout.",
            "triceps overhead extension with rope - Gethin variation": "The overhead triceps extension is an isolation exercise that is performed with a cable. It is usually performed for moderate to high reps as part of the arm-focused portion of a workout.",
            "machine triceps extension": "The machine triceps extension is an isolation exercise targeting the triceps muscles.",
            "machine triceps extension - Gethin variation": "The machine triceps extension is an isolation exercise targeting the triceps muscles.",
            "overhead machine triceps extension - Gethin variation": "The machine triceps extension is an isolation exercise targeting the triceps muscles.",
            "weighted bench dip": "The weighted bench dip is a highly effective exercise for building the triceps. The resistance comes from a combination of body weight and added weight—usually a weight plate.",
            "bodyweight triceps press": "The bodyweight triceps press is an arm movement that involves performing overhead presses in a face-down position on a Smith machine or other raised bar. It is a surprisingly difficult movement that hammers all three heads of the triceps and the difficulty can easily be scaled up or down by moving the bar.",
            "TBS dip": "The triceps dip is a machine version of an exercise that many lifters perform using parallel bars or two parallel benches. The machine is found in many gyms."
        }

    def run(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: dict) -> list:
        user_message = tracker.latest_message.get('text')
        exercise_name = self.extract_exercise_name(user_message)
        exercise_info = self.exercise_data.get(exercise_name.lower(), "Sorry, I don't have information about that exercise.")
        dispatcher.utter_message(text=exercise_info)
        return []

    def extract_exercise_name(self, user_message):
        for exercise in self.exercise_data.keys():
            if exercise in user_message.lower():
                return exercise
        return ""